#
# Policy to read and write in the client user table (dynamodb)
#
Resources:
  EndUserTableReadWritePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: "policy-end-user-table-access-${self:custom.conf.stage}"
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "dynamodb:BatchGetItem"
              - "dynamodb:BatchWriteItem"
              - "dynamodb:DeleteItem"
              - "dynamodb:DescribeTable"
              - "dynamodb:GetItem"
              - "dynamodb:GetRecords"
              - "dynamodb:PutItem"
              - "dynamodb:Query"
              - "dynamodb:Scan"
              - "dynamodb:UpdateItem"
            Resource:
              - "Fn::Sub": 'arn:aws:dynamodb:*:${AWS::AccountId}:table/${self:custom.conf.endUserTableName}'
              - "Fn::Sub": 'arn:aws:dynamodb:*:${AWS::AccountId}:table/${self:custom.conf.endUserTableName}/index/*'