#
# user table in dynamodb for piketto client app users management
#
Resources:
  EndUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.conf.endUserTableName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  UserTableArn:
    Value:
      Fn::GetAtt:
      - EndUserTable
      - Arn
    Export:
      Name: table-${self:custom.conf.api_name}-EndUserTableArn-${self:custom.conf.stage}