#
# Bucket access policy for images bucket
#
Resources:
  ImagesBucketAccessPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: "policy-images-bucket-access-${self:custom.conf.stage}"
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:ListBucket"
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:DeleteObject"
            Resource:
              # Bucket level operations
              - Fn::Join: [
                "", [
                  "arn:aws:s3:::",
                  {
                    "Ref" : S3ImagesBucket
                  }
                ]
              ]
              # Operations inside bucket
              - Fn::Join: [
                "", [
                  "arn:aws:s3:::",
                  {
                    "Ref" : S3ImagesBucket
                  },
                  "/*"
                ]
              ]